# Generated by Django 6.1 on 2026-09-05 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_negocio'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoservicio',
            name='categoria_item',
            field=models.CharField(blank=True, choices=[('electronica', 'Electrónica')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productoservicio',
            name='categoria_prod_servicio',
            field=models.CharField(blank=True, choices=[('producto', 'Producto'), ('servicio', 'Servicio')], max_length=255, null=True),
        ),
    ]
