# Generated by Django 6.1 on 2026-09-05 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_productoservicio_categoria_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoservicio',
            name='categoria_item',
            field=models.CharField(blank=True, choices=[('profesional', 'Profesional'), ('gaming', 'Gaming'), ('estudiante', 'Estudiante')], max_length=255, null=True),
        ),
    ]
